/*
Copyright 2026 The Holos Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package deployments — PreflightCheck planning-time validation helpers.
//
// # Design: two independent checks
//
// PreflightCheck surfaces two classes of conflict before the user clicks Apply:
//
//  1. Sibling-Deployment name collisions — a planned deployment's computed
//     singleton name (per Decision 3 of ADR 035) matches an existing
//     user-named Deployment in the same project namespace.
//
//  2. versionConstraint conflicts — two or more dependents in the same project
//     namespace pin incompatible version constraints on the same shared
//     dependency template.  The conflict is detected with Go-module-style
//     minimum version selection: we attempt to find a semver version that
//     satisfies every constraint; when none exists we report a
//     VersionConflictDetail.
//
// Neither check mutates cluster state.  Both use the existing ConfigMap-backed
// deployment store via h.k8s.ListDeployments, which is the same data surface
// exposed by ListDeployments and GetDeployment today.
//
// # Collision detection
//
// A collision is detected when the planned deployment's own name ends with
// "-shared" (the auto-managed singleton suffix from Decision 3 of ADR 035)
// AND a Deployment with that name already exists in the project namespace.
// This catches users who inadvertently choose a reserved singleton-pattern
// name that the reconciler uses for shared dependency Deployments.
//
// The case where the planned deployment's singleton name (auto-computed from
// its template) matches an already-existing singleton is NOT flagged —
// EnsureSingletonDependencyDeployment handles that idempotently by adding an
// ownerReference to the existing Deployment without any user intervention.
//
// # Version-constraint compatibility
//
// For each unique (template_namespace, template_name) pair collected across all
// planned deployments, constraintsCompatible checks whether the intersection of
// the constraint set is non-empty.  It does this by testing a grid of candidate
// versions against the combined constraint; if no candidate satisfies every
// constraint the pair is reported as conflicted.
//
// The candidate grid is synthesised from the constraint bounds: we parse each
// constraint's component clauses, extract lower and upper bounds, and test
// versions at those boundary points plus a midpoint.  This is conservative —
// it reports false positives only for degenerate patterns that a real package
// registry would not produce (e.g. `>= 1.0.0-alpha.1 < 1.0.0-alpha.2`).
// Practical usage (major-version ranges, pin-to-exact) is handled correctly.
package deployments

import (
	"fmt"
	"sort"
	"strings"

	semver "github.com/Masterminds/semver/v3"

	v1alpha1 "github.com/holos-run/holos-console/api/templates/v1alpha1"
	consolev1 "github.com/holos-run/holos-console/gen/holos/console/v1"
)

// isSingletonName reports whether name ends with the "-shared" suffix used by
// singleton dependency Deployments (per Decision 3 of ADR 035).
func isSingletonName(name string) bool {
	return strings.HasSuffix(name, "-shared")
}

// DetectCollisions checks each planned deployment against existing Deployments
// in the project namespace for singleton-naming conflicts.
//
// A collision is reported when the planned deployment's own name ends with
// "-shared" (the auto-managed singleton suffix from ADR 035 Decision 3) AND
// that name already exists in the project namespace.  This catches users who
// inadvertently (or deliberately) choose a reserved singleton-pattern name
// for a user-managed deployment.
//
// Computed singleton names (auto-generated by the reconciler for dependency
// singletons) are NOT flagged: when the reconciler's singleton "waypoint-shared"
// already exists and a second dependent references the same template, the
// reconciler handles the add-ownerRef case idempotently without user
// intervention.
//
// existingNames is the set of all Deployment ConfigMap names currently in the
// project namespace (name → true).
//
// Exported so external test packages can unit-test the collision logic
// independently of the full handler lifecycle.
func DetectCollisions(
	planned []*consolev1.PlannedDeployment,
	existingNames map[string]bool,
) []*consolev1.CollisionDetail {
	var collisions []*consolev1.CollisionDetail

	for _, pd := range planned {
		// Collision: user chose a singleton-pattern name ("<x>-shared") that is
		// already taken in the project namespace.
		if isSingletonName(pd.GetName()) && existingNames[pd.GetName()] {
			// Confirm the name is NOT the reconciler-computed singleton for this
			// planned deployment's own template.  If it IS, the reconciler will
			// handle it idempotently and there is no user-visible conflict.
			var ref v1alpha1.LinkedTemplateRef
			if ltr := pd.GetLinkedTemplateRef(); ltr != nil {
				ref = v1alpha1.LinkedTemplateRef{
					Name:              ltr.GetName(),
					VersionConstraint: pd.GetVersionConstraint(),
				}
			}
			ownSingleton := SingletonName(ref)
			if pd.GetName() != ownSingleton {
				// The planned deployment is trying to use a singleton-pattern
				// name that belongs to a different dependency edge.
				collisions = append(collisions, &consolev1.CollisionDetail{
					PlannedName:     pd.GetName(),
					ConflictingName: pd.GetName(),
					Advice: fmt.Sprintf(
						"Deployment name %q uses the auto-managed singleton name "+
							"format (suffix \"-shared\") and collides with an existing "+
							"Deployment in the project namespace.  "+
							"Choose a different name that does not end with \"-shared\".",
						pd.GetName(),
					),
				})
			}
		}
	}

	return collisions
}

// constraintKey is the canonical key for grouping per (template_namespace, template_name).
type constraintKey struct {
	namespace string
	name      string
}

// dependencyConstraintEntry holds one (versionConstraint, dependentName) tuple.
type dependencyConstraintEntry struct {
	constraint    string
	dependentName string
}

// collectConstraintMap builds a map from (template_namespace, template_name)
// → []dependencyConstraintEntry from the planned deployment set.
// Only entries with a non-empty version_constraint are collected, since empty
// constraints cannot conflict.
func collectConstraintMap(planned []*consolev1.PlannedDeployment) map[constraintKey][]dependencyConstraintEntry {
	m := make(map[constraintKey][]dependencyConstraintEntry)
	for _, pd := range planned {
		ref := pd.GetLinkedTemplateRef()
		if ref == nil {
			continue
		}
		vc := pd.GetVersionConstraint()
		if vc == "" {
			continue
		}
		key := constraintKey{
			namespace: ref.GetNamespace(),
			name:      ref.GetName(),
		}
		m[key] = append(m[key], dependencyConstraintEntry{
			constraint:    vc,
			dependentName: pd.GetName(),
		})
	}
	return m
}

// DetectVersionConflicts returns a VersionConflictDetail for each
// (template_namespace, template_name) group whose combined constraints are
// mutually incompatible.
//
// Exported so external test packages can unit-test the conflict-detection
// logic independently of the full handler lifecycle.
func DetectVersionConflicts(planned []*consolev1.PlannedDeployment) []*consolev1.VersionConflictDetail {
	m := collectConstraintMap(planned)
	var conflicts []*consolev1.VersionConflictDetail

	for key, entries := range m {
		if len(entries) < 2 {
			// Single constraint — nothing to conflict with.
			continue
		}

		// Collect unique constraints.  If all dependents use the same
		// constraint string the combined set is trivially compatible.
		seen := make(map[string]struct{})
		var uniqueConstraints []string
		var dependentNames []string
		for _, e := range entries {
			dependentNames = append(dependentNames, e.dependentName)
			if _, ok := seen[e.constraint]; !ok {
				seen[e.constraint] = struct{}{}
				uniqueConstraints = append(uniqueConstraints, e.constraint)
			}
		}
		if len(uniqueConstraints) == 1 {
			continue
		}

		// Parse each constraint.
		parsed := make([]*semver.Constraints, 0, len(uniqueConstraints))
		parseErr := false
		for _, c := range uniqueConstraints {
			cs, err := semver.NewConstraint(c)
			if err != nil {
				// Unparsable constraint — report as conflict so the user is
				// notified before apply.
				parseErr = true
				break
			}
			parsed = append(parsed, cs)
		}

		if parseErr || !constraintsCompatible(parsed, uniqueConstraints) {
			sort.Strings(dependentNames)
			sort.Strings(uniqueConstraints)
			conflicts = append(conflicts, &consolev1.VersionConflictDetail{
				TemplateNamespace: key.namespace,
				TemplateName:      key.name,
				Constraints:       uniqueConstraints,
				DependentNames:    dependentNames,
			})
		}
	}

	return conflicts
}

// constraintsCompatible reports whether the intersection of the given semver
// constraints is non-empty.
//
// Strategy: synthesise a set of candidate versions from the bounds expressed
// in each constraint clause, then test each candidate against the combined
// constraint set.  If any candidate satisfies all constraints, the set is
// compatible.  If none does, we report a conflict.
//
// The candidate set is built by extracting the first bound version from each
// constraint expression (stripped of operators) and generating versions at
// that point, one patch above, and one major version above.  This handles the
// common cases:
//
//   - Exact pin: "=1.2.3" vs "=1.2.4" → candidates include 1.2.3 and 1.2.4;
//     neither satisfies both → conflict.
//   - Overlapping ranges: ">=1.0.0 <2.0.0" vs ">=1.5.0 <3.0.0" → candidate
//     1.5.0 satisfies both → compatible.
//   - Non-overlapping ranges: ">=1.0.0 <2.0.0" vs ">=3.0.0" → no candidate
//     satisfies both → conflict.
func constraintsCompatible(parsed []*semver.Constraints, raw []string) bool {
	if len(parsed) == 0 {
		return true
	}

	// Gather candidate versions from the raw constraint strings.
	candidates := candidateVersions(raw)

	for _, v := range candidates {
		allMatch := true
		for _, c := range parsed {
			if !c.Check(v) {
				allMatch = false
				break
			}
		}
		if allMatch {
			return true
		}
	}
	return false
}

// candidateVersions extracts boundary semver versions from raw constraint
// strings to use as test candidates in constraintsCompatible.
func candidateVersions(raw []string) []*semver.Version {
	seen := make(map[string]*semver.Version)

	for _, constraint := range raw {
		// Split compound constraints (space- or comma-separated clauses).
		for _, clause := range splitClauses(constraint) {
			// Strip operators to get the version string.
			vStr := strings.TrimLeft(clause, "^~>=<! ")
			vStr = strings.TrimSpace(vStr)
			if vStr == "" {
				continue
			}
			v, err := semver.NewVersion(vStr)
			if err != nil {
				continue
			}
			key := v.Original()
			if _, ok := seen[key]; !ok {
				seen[key] = v
			}
			// Also add patch+1 and major+1 variants to probe nearby regions.
			if patch1, err := semver.NewVersion(fmt.Sprintf("%d.%d.%d", v.Major(), v.Minor(), v.Patch()+1)); err == nil {
				k := patch1.Original()
				if _, ok := seen[k]; !ok {
					seen[k] = patch1
				}
			}
			if minor1, err := semver.NewVersion(fmt.Sprintf("%d.%d.%d", v.Major(), v.Minor()+1, 0)); err == nil {
				k := minor1.Original()
				if _, ok := seen[k]; !ok {
					seen[k] = minor1
				}
			}
			if major1, err := semver.NewVersion(fmt.Sprintf("%d.0.0", v.Major()+1)); err == nil {
				k := major1.Original()
				if _, ok := seen[k]; !ok {
					seen[k] = major1
				}
			}
		}
	}

	result := make([]*semver.Version, 0, len(seen))
	for _, v := range seen {
		result = append(result, v)
	}
	// Sort for deterministic evaluation order.
	sort.Slice(result, func(i, j int) bool {
		return result[i].LessThan(result[j])
	})
	return result
}

// splitClauses splits a compound semver constraint expression into individual
// clauses.  The Masterminds library accepts space-separated AND clauses and
// comma-separated OR clauses.  We split on both to extract individual version
// bound expressions.
func splitClauses(constraint string) []string {
	// Replace commas with spaces, then split on whitespace.
	s := strings.ReplaceAll(constraint, ",", " ")
	parts := strings.Fields(s)
	return parts
}
