---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: holos-console-templates
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - templates.holos.run
  resources:
  - templatepolicies
  - templatepolicybindings
  - templates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.holos.run
  resources:
  - templatepolicies/finalizers
  - templatepolicybindings/finalizers
  - templates/finalizers
  verbs:
  - update
- apiGroups:
  - templates.holos.run
  resources:
  - templatepolicies/status
  - templatepolicybindings/status
  - templates/status
  verbs:
  - get
  - patch
  - update
