---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: holos-console-templates
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - groups
  - users
  verbs:
  - impersonate
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - impersonate
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  - deployments.holos.run
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.holos.run
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.holos.run
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  - referencegrants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - roles
  verbs:
  - bind
  - create
  - delete
  - escalate
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.holos.run
  resources:
  - renderstates
  - templatedependencies
  - templatepolicies
  - templatepolicybindings
  - templatereleases
  - templaterequirements
  - templates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.holos.run
  resources:
  - renderstates/finalizers
  - templatedependencies/finalizers
  - templatepolicies/finalizers
  - templatepolicybindings/finalizers
  - templatereleases/finalizers
  - templaterequirements/finalizers
  - templates/finalizers
  verbs:
  - update
- apiGroups:
  - templates.holos.run
  resources:
  - renderstates/status
  - templatedependencies/status
  - templategrants/status
  - templatepolicies/status
  - templatepolicybindings/status
  - templatereleases/status
  - templaterequirements/status
  - templates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - templates.holos.run
  resources:
  - templategrants
  verbs:
  - get
  - list
  - watch
